knp_snappy:
    pdf:
        enabled:    true
        binary:     "wkhtmltopdf"
        options:    []
    image:
        enabled:    true
        binary:     "%kernel.root_dir%/../vendor/wemersonjanuario/wkhtmltopdf-windows/bin/64bit/wkhtmltopdf.exe"
        options:    []
    temporary_folder: "%kernel.cache_dir%/snappy"
    process_timeout: 20 # In seconds