security:
    encoders:
        FOS\UserBundle\Model\UserInterface: auto

    role_hierarchy:
        ROLE_ENSEIGNANT_PRIMAIRE: [ROLE_USER]
        ROLE_ENSEIGNANT_SECONDAIRE: [ROLE_USER]
        ROLE_ENSEIGNANT_SUPERIEUR: [ROLE_USER]
        ROLE_GERANT_TRANPORT_PRIMAIRE: [ROLE_USER]
        ROLE_GERANT_TRANPORT_SECONDAIRE: [ROLE_USER]
        ROLE_GERANT_TRANPORT_SUPERIEUR: [ROLE_USER]
        ROLE_GERANT_CANTINE_PRIMAIRE: [ROLE_USER]
        ROLE_GERANT_CANTINE_SECONDAIRE: [ROLE_USER]
        ROLE_GERANT_CANTINE_SUPERIEUR: [ROLE_USER]
        ROLE_CAISSIER_PRIMAIRE: [ROLE_USER]
        ROLE_CAISSIER_SECONDAIRE: [ROLE_USER]
        ROLE_CAISSIER_SUPERIEUR: [ROLE_USER]
        ROLE_COMPTABLE_PRIMAIRE: [ROLE_USER]
        ROLE_COMPTABLE_SECONDAIRE: [ROLE_USER]
        ROLE_COMPTABLE_SUPERIEUR: [ROLE_USER]
        ROLE_SURVEILLANT_PRIMAIRE: [ROLE_USER]
        ROLE_SURVEILLANT_SECONDAIRE: [ROLE_USER]
        ROLE_SURVEILLANT_SUPERIEUR: [ROLE_USER]
        ROLE_CENSEUR_PRIMAIRE: [ROLE_USER]
        ROLE_CENSEUR_SECONDAIRE: [ROLE_USER]
        ROLE_CENSEUR_SUPERIEUR: [ROLE_USER]
        ROLE_DIRECTEUR_PRIMAIRE: [ROLE_USER]
        ROLE_DIRECTEUR_SECONDAIRE: [ROLE_USER]
        ROLE_DIRECTEUR_SUPERIEUR: [ROLE_USER]
        ROLE_ADMIN_PRIMAIRE: [ROLE_USER]
        ROLE_ADMIN_SECONDAIRE: [ROLE_USER]
        ROLE_ADMIN_SUPERIEUR: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER]

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            user_checker: fos_user.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
