<?php

namespace App\Constante;

class Constantes {

    const ROLE_SUPER_ADMIN = "ROLE_SUPER_ADMIN";

    const ROLE_ADMIN_SUPERIEUR = "ROLE_ADMIN_SUPERIEUR";
    const ROLE_ADMIN_SECONDAIRE = "ROLE_ADMIN_SECONDAIRE";
    const ROLE_ADMIN_PRIMAIRE = "ROLE_ADMIN_PRIMAIRE";

    const ROLE_DIRECTEUR_SUPERIEUR = "ROLE_DIRECTEUR_SUPERIEUR";
    const ROLE_DIRECTEUR_SECONDAIRE = "ROLE_DIRECTEUR_SECONDAIRE";
    const ROLE_DIRECTEUR_PRIMAIRE = "ROLE_DIRECTEUR_PRIMAIRE";

    const ROLE_CENSEUR_SUPERIEUR = "ROLE_CENSEUR_SUPERIEUR";
    const ROLE_CENSEUR_SECONDAIRE = "ROLE_CENSEUR_SECONDAIRE";
    const ROLE_CENSEUR_PRIMAIRE = "ROLE_CENSEUR_PRIMAIRE";

    const ROLE_SURVEILLANT_SUPERIEUR = "ROLE_SURVEILLANT_SUPERIEUR";
    const ROLE_SURVEILLANT_SECONDAIRE = "ROLE_SURVEILLANT_SECONDAIRE";
    const ROLE_SURVEILLANT_PRIMAIRE = "ROLE_SURVEILLANT_PRIMAIRE";

    const ROLE_COMPTABLE_SUPERIEUR = "ROLE_COMPTABLE_SUPERIEUR";
    const ROLE_COMPTABLE_SECONDAIRE = "ROLE_COMPTABLE_SECONDAIRE";
    const ROLE_COMPTABLE_PRIMAIRE = "ROLE_COMPTABLE_PRIMAIRE";

    const ROLE_CAISSIER_SUPERIEUR = "ROLE_CAISSIER_SUPERIEUR";
    const ROLE_CAISSIER_SECONDAIRE = "ROLE_CAISSIER_SECONDAIRE";
    const ROLE_CAISSIER_PRIMAIRE = "ROLE_CAISSIER_PRIMAIRE";

    const ROLE_GERANT_CANTINE_SUPERIEUR = "ROLE_GERANT_CANTINE_SUPERIEUR";
    const ROLE_GERANT_CANTINE_SECONDAIRE = "ROLE_GERANT_CANTINE_SECONDAIRE";
    const ROLE_GERANT_CANTINE_PRIMAIRE = "ROLE_GERANT_CANTINE_PRIMAIRE";

    const ROLE_GERANT_TRANPORT_SUPERIEUR = "ROLE_GERANT_TRANPORT_SUPERIEUR";
    const ROLE_GERANT_TRANPORT_SECONDAIRE = "ROLE_GERANT_TRANPORT_SECONDAIRE";
    const ROLE_GERANT_TRANPORT_PRIMAIRE = "ROLE_GERANT_TRANPORT_PRIMAIRE";

    const ROLE_ENSEIGNANT_SUPERIEUR = "ROLE_ENSEIGNANT_SUPERIEUR";
    const ROLE_ENSEIGNANT_SECONDAIRE = "ROLE_ENSEIGNANT_SECONDAIRE";
    const ROLE_ENSEIGNANT_PRIMAIRE = "ROLE_ENSEIGNANT_PRIMAIRE";

   
   // const ROLE_FINANCIERE = "ROLE_FINANCIERE";
   //const ROLE_CLIENT = "ROLE_CLIENT";
   // const ROLE_POMPISTE = "ROLE_POMPISTE";
   // const ROLE_GERANT = "ROLE_GERANT";
   // const VALEUR_CATEGORIE1 = 10000;
   // const VALEUR_CATEGORIE2 = 5000;
   // const VALEUR_CATEGORIE3 = 2500;
   // const VALEUR_CATEGORIE4 = 1000;
   // const GESTIONNAIRE = "GESTIONNAIRE";
   // const FINANCIERE = "FINANCIERE";
   // const CLIENT = "CLIENT";
   // const POMPISTE = "POMPISTE";
   // const TVA = '0.19';
   // const GERANT = "GERANT";

}